name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and push backend image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: nessimntambi/loan_backend:latest
        build-args: |
          ASPNETCORE_ENVIRONMENT=Production
          DB_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING }}


    - name: Build and push migrations image
      run: |
        docker build --target migrations --args "ASPNETCORE_ENVIRONMENT=Production,DB_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING }}"  -t "${{secrets.DOCKERHUB_USERNAME}}"/loan_backend_migrations:latest .
        docker push "${{secrets.DOCKERHUB_USERNAME}}"/loan_backend_migrations:latest
      
    - name: Run migrations
      run: |
        docker run --rm \
          -e DB_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING }} \
          nessimntambi/loan_backend_migrations:latest \
          database update

