name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and push backend image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: nessimntambi/loan_backend:latest
        build-args: |
          ASPNETCORE_ENVIRONMENT=Production
          DBCONNECTION=${{ secrets.DBCONNECTION }}

    - name: Build and push CC backend image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: nessimntambi/lms-cc-back:latest
        build-args: |
          ASPNETCORE_ENVIRONMENT=Production
          DBCONNECTION=${{ secrets.DBCONNECTION }}


    - name: Build and push migrations image
      run: |
        docker build --target migrations \
        -t ${{secrets.DOCKERHUB_USERNAME}}/loan_backend_migrations:latest .
    
        docker push ${{secrets.DOCKERHUB_USERNAME}}/loan_backend_migrations:latest
      
    - name: Run migrations
      run: |
        echo "DBCONNECTION=${{ secrets.DBCONNECTION }}" >> $GITHUB_ENV  # Add DB connection string as environment variable
        docker run --env DBCONNECTION nessimntambi/loan_backend_migrations:latest database update --connection "${{secrets.DBCONNECTION}}"
           

